// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CurrencyApi.Models
{
    public partial class DtbankdbContext : DbContext
    {
        public virtual DbSet<RATE> RATE { get; set; }

        public DtbankdbContext(DbContextOptions<DtbankdbContext> options) : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<RATE>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(36)
                    .HasDefaultValueSql("(newid())");

                entity.Property(e => e.Country).HasMaxLength(3);

                entity.Property(e => e.Name).HasMaxLength(50);

                entity.Property(e => e.Rate1)
                    .HasColumnName("Rate")
                    .HasColumnType("money");

                entity.Property(e => e.TimeStamp)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingExt(modelBuilder);
        }

        partial void OnModelCreatingExt(ModelBuilder modelBuilder);
    }
}